# Generated by Django 4.1.7 on 2023-03-12 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tier_name", models.CharField(max_length=256)),
                ("thumbnail_size", models.IntegerField(null=True)),
                ("presence_of_original_link", models.BooleanField(default=False)),
                ("ability_to_expiring_links", models.BooleanField(default=False)),
            ],
        ),
    ]
