# Generated by Django 4.1.7 on 2023-03-12 11:57

import apps.tiers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_tier',
            field=models.ForeignKey(default=apps.tiers.models.AccountTier.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='tiers.accounttier'),
        ),
    ]
