# Generated by Django 4.1.7 on 2023-03-12 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("images_api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="uploading_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="thumbnail",
            name="original_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="images_api.uploadedimage",
            ),
        ),
    ]
